### ISSUE TITLE
Montagem do Relatório

### ISSUE THREAD

**Issue by thiagonegreiros** [thiagonegreiros/aula-reforco#6]
The document are in this link: [Resume 1J2T3D](https://liveestacio-my.sharepoint.com/:w:/g/personal/202008421144_alunos_estacio_br/EZ9WT0e8oStDhWaNzUOKRq4B_vHz4dJ4cpLh_Zi7K6mKwA?e=QDSpBJ)

**Comment by juarezfilhoii** [comment]
Item 1 - Identificação das partes envolvidas e parceiros
